security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        administrators:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            provider: administrators
            pattern:  ^/([a-z]*/)?game
            form_login:
                check_path: login_check
                login_path: login
                default_target_path: game_home
                always_use_default_target_path: true
            logout:
                path: logout
                target: login

        main:
            anonymous: ~
